### PR TITLE
Bug 1717771 - Use relative font sizes and line heights rather than fixed sizes.

### PR DESCRIPTION
**Pull request by Standard8**
This helps to accommodate different user's preferences for email font size.

### CODE REVIEW

**Comment by Standard8** [comment]
I'm not quite sure if we should also make all the other sizes relative as well, but I think this would be a good start.

**Comment by mitchhentges** [comment]
Interesting, thanks!
Two questions:
* I wonder if `em` would be more idiomatic than percentages here.
* Which client are you using, and how have you set a different font size? I'd like to take a look locally :)

**Comment by Standard8** [comment]
>     * I wonder if `em` would be more idiomatic than percentages here.

Could be, I'm happy for either.

>     * Which client are you using, and how have you set a different font size? I'd like to take a look locally :)

Thunderbird 78 plus [Conversations](https://addons.thunderbird.net/thunderbird/addon/gmail-conversation-view/).

Conversations has a function to that changes the message font size which makes it slightly smaller to fit with the rest of the UI (can be turned off in its preferences).

The default font size in Thunderbird is set in preferences - it should affect both the normal message display and the Conversations display. If you're experimenting, it is probably easiest to test only Thunderbird.

For setting the font size for Phabricator emails, I think you want:

* Preferences (or options)
* General
* Language & Appearance -> Fonts & Colours

I think you'll be able to change the font size in the drop-down there.

If that doesn't work (with a fixed Phab email):
* Go to Advanced
* For the `Fonts for` selection at the top, select `Other Writing Systems`
* Then change the `Size` next to the `Proportional` option.

You can also use devtools to inspect and play.

**Comment by mitchhentges** [comment]
Nice, thanks!
I need to investigate some more pressing tickets around phab-emails, but I'll come back to test and review this after our break :)

**Comment by mitchhentges** [comment]
I like the approach of using relative font sizes, but this PR accidentally causes breaking design changes (font is significantly smaller) for users who are still using default font sizes in GMail/Thunderbird.

I'll provide my patch here shortly to rectify this.
Thanks again for the initial patch :+1:

**Pull request closed without merging**
