### PR TITLE
Bug 1718237 - Reduce linkified content in the email title section.

### PR DESCRIPTION
**Pull request by Standard8**

### CODE REVIEW

**Comment by Standard8** [comment]
See the [bug for a comparison screenshot](https://bugzilla.mozilla.org/show_bug.cgi?id=1718237).

**Review by mitchhentges — APPROVED** [review]
This looks good to me :+1: 
Can you rebase this and re-push so that CI will be triggered?

**Comment by Standard8** [comment]
@mitchhentges I've rebased and pushed. Looks like CI is still running.

**Comment by mitchhentges** [comment]
@Standard8 can you push one more time? CircleCI didn't want to build for forks :)

**Comment by Standard8** [comment]
@mitchhentges done. Looks like it is running this time :)

**Comment by mitchhentges** [comment]
Perfect, thanks Mark!

**Pull request merged**
